# License:
# **********************************************
# 
# src/Code/Project/Kthura_Transfer_TFT.ini
# (c) Jeroen Broks, 2026, All Rights Reserved.
# 
# This file contains material that is related
# to a storyline that is which is strictly
# copyrighted to Jeroen Broks.
# 
# This file may only be used in an unmodified
# form with an unmodified version of the
# software this file belongs to.
# 
# You may use this file for your study to see
# how I solved certain things in the creation
# of this project to see if you find valuable
# leads for the creation of your own.
# 
# Mostly this file comes along with a project
# that is for most part released under an
# open source license and that means that if
# you use that code with this file removed
# from it, you can use it under that license.
# Please check out the other files to find out
# which license applies.
# 
# This file comes 'as-is' and in no possible
# way the author can be held responsible of
# any form of damages that may occur due to
# the usage of this file
# 
# 
# **********************************************
# 
# 
# version: 26.02.25 IV
# 
# End License
# Kthura Transfer Project File

[AUTHORS]
GR-SITES=GR-Sites
JEROEN P. BROKS=Tricky - Private
MAN OF STEEL=Man Of Steel
OCAL (UNKNOWN ARTIST)=
[CUSTOMKIND]
ALL=Y
ANY=Y
[MAPMETA]
ALL=Y
ANY=Y
[ORIGINAL]
KTHURADIR=/media/tricky/Scyndi/Projects/Applications/Apollo/Games/The Fairy Tale Revamped/src/Tricky Private/Kthura
TEXTUREJCR6=/media/tricky/Scyndi/Projects/Applications/Apollo/Games/The Fairy Tale Revamped/Debug/The Fairy Tale REVAMPED.jcr
[PROJECT]
CREATED=26 Jun 2025; 22:39:35
[RENAME]
ANNA=Anna
CH1_DUNGEON_FRENDORBUSHES=CH1_Dungeon_FrendorBushes
CH1_DUNGEON_HELL=CH1_Dungeon_Hell
CH1_DUNGEON_HOLYPATH=CH1_Dungeon_HolyPath
CH1_DUNGEON_LIBRARY=CH1_Dungeon_Library
CH1_DUNGEON_LIBRARY.=CH1_Dungeon_Library
CH1_DUNGEON_SUBRIVER=CH1_Dungeon_SubRiver
CH1_HUB_ALTAR=CH1_Hub_Altar
CH1_HUB_JAKEHUT=CH1_Hub_JakeHut
CH2_DUNGEON_DRAGONCASTLE=CH2_Dungeon_DragonCastle
CH2_DUNGEON_ELFROAD=CH2_Dungeon_ElfRoad
CH2_TOWN_ISKARDERIU=CH2_Town_Iskarderiu
PRO_DUNGEON_CRYPT=PRO_Dungeon_Crypt
PRO_DUNGEON_DRAGONCAVE=PRO_Dungeon_DragonCave
PRO_DUNGEON_MAGIC=PRO_Dungeon_Magic
PRO_DUNGEON_TOMB=PRO_Dungeon_Tomb
PRO_EMPTY=PRO_Empty
PRO_HUB_WENIARIA=PRO_Hub_Weniaria
PRO_THEEND=PRO_TheEnd
PRO_TOWN_FRENDOR=PRO_Town_Frendor
PRO_TOWN_VANDAR=PRO_Town_Vandar
[TARGET]
AUTHOR=Jeroen P. Broks
KTHURADIR=src/Kthura
NOTES=Owned and copyrighted by Jeroen P. Broks. May NOT be extracted from this project without PRIOR written notice from Jeroen P. Broks
SOURCEASSETS=src/Assets
STORAGE=zlib
TEXTUREJCR6=Debug/The Fairy Tale.jql
[TEXCONV]
GFX/ACTORS/BUNDLED/PLAYER/HANDOSTILLOR.WEST.JPBF=GFX/ACTORS/BUNDLED/PLAYER/HandoStillor.WEST.jpbf
GFX/ACTORS/SINGLE/ANNA/ANNA MONK FEMALE DWARF.PNG=GFX/Actors/Single/Anna/Anna Monk Female Dwarf.png
GFX/ACTORS/SINGLE/ANNA/ANNA MONK FEMALE ELF.PNG=GFX/Actors/Single/Anna/Anna Monk Female Elf.png
GFX/ACTORS/SINGLE/ANNA/ANNA MONK FEMALE FAIRY.PNG=GFX/Actors/Single/Anna/Anna Monk Female Fairy.png
GFX/ACTORS/SINGLE/ANNA/ANNA MONK FEMALE HUMAN.PNG=GFX/Actors/Single/Anna/Anna Monk Female Human.png
GFX/ACTORS/SINGLE/BLACK WINGED FAIRIES/FEMALE 3.PNG=GFX/NPC/Black Winged Fairies/ZZ Female 3.png
GFX/ACTORS/SINGLE/DARKELVES/MELODY.PNG=GFX/Actors/Single/DarkElves/Melody.png
GFX/ACTORS/SINGLE/DEMO/BOUWVAKKER.PNG=GFX/Actors/Single/Demo/Bouwvakker.png
GFX/ACTORS/SINGLE/ELVES/GEDRIOFULLA.PNG=GFX/Actors/Single/Elves/GedrioFulla.png
GFX/ACTORS/SINGLE/ELVES/RANDOMELFFEMALE.PNG=GFX/Actors/Single/Elves/RandomElfFemale.png
GFX/ACTORS/SINGLE/ELVES/RANDOMELFFEMALE2.PNG=GFX/Actors/Single/Elves/RandomElfFemale2.png
GFX/ACTORS/SINGLE/ELVES/RANDOMELFMALE.PNG=GFX/Actors/Single/Elves/RandomElfMale.png
GFX/ACTORS/SINGLE/ELVES/RANDOMELFMALE2.PNG=GFX/Actors/Single/Elves/RandomElfMale2.png
GFX/ACTORS/SINGLE/ELVES/SASHAFUNDA.NORTH.PNG=GFX/Actors/Single/Elves/SashaFunda.North.png
GFX/ACTORS/SINGLE/ELVES/SASHAFUNDA.SOUTH.PNG=GFX/Actors/Single/Elves/SashaFunda.South.png
GFX/ACTORS/SINGLE/ELVES/WALDA.PNG=GFX/Actors/Single/Elves/Walda.png
GFX/ACTORS/SINGLE/FAIRIES/ASKLEPIA.PNG=GFX/Actors/Single/Fairies/Asklepia.png
GFX/ACTORS/SINGLE/FAIRIES/FAIRYKID.PNG=GFX/Actors/Single/Fairies/FairyKid.png
GFX/ACTORS/SINGLE/FAIRIES/FANDALORA.PNG=GFX/Actors/Single/Fairies/Fandalora.png
GFX/ACTORS/SINGLE/FAIRIES/FEENALARIA.PNG=GFX/Actors/Single/Fairies/Feenalaria.png
GFX/ACTORS/SINGLE/FAIRIES/FEMALE2.PNG=GFX/Actors/Single/Fairies/Female2.png
GFX/ACTORS/SINGLE/FAIRIES/FEMALE3.PNG=GFX/Actors/Single/Fairies/Female3.png
GFX/ACTORS/SINGLE/FAIRIES/FREYA.PNG=GFX/Actors/Single/Fairies/Freya.png
GFX/ACTORS/SINGLE/FAIRIES/MALE.PNG=GFX/Actors/Single/Fairies/Male.png
GFX/ACTORS/SINGLE/FAIRIES/MALE2.PNG=GFX/Actors/Single/Fairies/Male.png
GFX/ACTORS/SINGLE/FAIRIES/NOSTRAMANTU.PNG=GFX/Actors/Single/Fairies/Nostramantu.png
GFX/ACTORS/SINGLE/FAIRIES/NOSTRAMANTU_BACKSIDE.PNG=GFX/Actors/Single/Fairies/Nostramantu_Backside.png
GFX/ACTORS/SINGLE/FAIRIES/TAI.PNG=GFX/Actors/Single/Fairies/Tai.png
GFX/ACTORS/SINGLE/FAIRIES/YANEE.PNG=GFX/Actors/Single/Fairies/Yanee.png
GFX/ACTORS/SINGLE/HUMANS/CHIEFWERRINGTON.PNG=GFX/NPC/Humans/Chief Werrington.png
GFX/ACTORS/SINGLE/HUMANS/FEMALE.PNG=GFX/NPC/Humans/ZZ Female 1.png
GFX/ACTORS/SINGLE/HUMANS/GIRL.PNG=GFX/NPC/Humans/Girl 1.png
GFX/ACTORS/SINGLE/HUMANS/GUARD.PNG=GFX/NPC/Humans/Guard
GFX/ACTORS/SINGLE/HUMANS/HARRY.PNG=GFX/NPC/Humans/Harry McDummy.png
GFX/ACTORS/SINGLE/HUMANS/HARRY_BACKSIDE.PNG=GFX/Actors/Single/Humans/Harry_BackSide.png
GFX/ACTORS/SINGLE/HUMANS/MALE.PNG=GFX/NPC/Humans/ZZ Male 1.png
GFX/ACTORS/SINGLE/HUMANS/MASTER JOHN.PNG=GFX/NPC/Humans/Master John.png
GFX/ACTORS/SINGLE/HUMANS/RUBINETHEHOOD.PNG=GFX/Actors/Single/Humans/RubineTheHood.png
GFX/ACTORS/SINGLE/HUMANS/SHOPHOER.PNG=GFX/Actors/Single/Humans/ShopHoer.png
GFX/ACTORS/SINGLE/HUMANS/THIEF.PNG=GFX/Actors/Single/Humans/Thief.png
GFX/BIG_CHAR/DANDOR.PNG=GFX/Big_Char/Dandor.png
GFX/BIG_CHAR/HANDO STILLOR.PNG=GFX/Big_Char/Hando Stillor.png
GFX/BIG_CHAR/JAKE.PNG=GFX/Big_Char/Jake.png
GFX/BIG_CHAR/JAKEMARRILONA.PNG=GFX/Big_Char/JakeMarrilona.png
GFX/BIG_CHAR/MARRILONA.PNG=GFX/Big_Char/Marrilona.png
GFX/COMBAT/FIGHTERS/FOE/BOSS/KILLERESCARGOT.PNG=GFX/COMBAT/FIGHTERS/FOE/BOSS/KILLERESCARGOT.PNG
GFX/COMBAT/FIGHTERS/FOE/BOSS/SHADOWSWEEPER.PNG=GFX/Combat/Fighters/Foe/Boss/ShadowSweeper.png
GFX/COMBAT/FIGHTERS/FOE/REG/ZOMBIE.PNG=GFX/Combat/Fighters/Foe/Reg/Zombie.png
GFX/COMBAT/FIGHTERS/HERO/MARRILONA.DEAD.PNG=GFX/Combat/Fighters/Hero/Marrilona.Dead.png
GFX/FIELD ICONS/FSORB.PNG=GFX/Field Icons/FSORB.png
GFX/LOGO/END OF PROLOGUE.PNG=GFX/Logo/End Of Prologue.png
GFX/LOGO/THE END.PNG=GFX/Logo/The End.png
GFX/MAPSPOTS/RECOVER.PNG=GFX/MapSpots/Recover.png
GFX/MAPSPOTS/SAVE.PNG=GFX/MapSpots/Save.png
GFX/MAPSPOTS/TRAVEL.PNG=GFX/MapSpots/Travel.png
GFX/TEXTURES/ALPHABETTILES/YURGONTILE.PNG=GFX/Textures/AlphabetTiles/YurgonTile.png
GFX/TEXTURES/ANNA/GIRL_HEAD.PNG=GFX/Textures/Anna/Girl_Head.png
GFX/TEXTURES/BOOKCASE/BOEKENKAST.PNG=GFX/Textures/Bookcase/Boekenkast.png
GFX/TEXTURES/CAVES/GREY + ALPHA/E.PNG=GFX/TEXTURES/CAVES/GREY + ALPHA/E.PNG
GFX/TEXTURES/CAVES/GREY + ALPHA/N.PNG=GFX/TEXTURES/CAVES/GREY + ALPHA/N.PNG
GFX/TEXTURES/CAVES/GREY + ALPHA/NE.PNG=GFX/TEXTURES/CAVES/GREY + ALPHA/NE.PNG
GFX/TEXTURES/CAVES/GREY + ALPHA/NW.PNG=GFX/TEXTURES/CAVES/GREY + ALPHA/NW.PNG
GFX/TEXTURES/CAVES/GREY + ALPHA/S.PNG=GFX/TEXTURES/CAVES/GREY + ALPHA/S.PNG
GFX/TEXTURES/CAVES/GREY + ALPHA/SE.PNG=GFX/TEXTURES/CAVES/GREY + ALPHA/SE.PNG
GFX/TEXTURES/CAVES/GREY + ALPHA/SE_F.PNG=GFX/TEXTURES/CAVES/GREY + ALPHA/SE_F.PNG
GFX/TEXTURES/CAVES/GREY + ALPHA/SHORE.PNG=GFX/TEXTURES/CAVES/GREY + ALPHA/SHORE.PNG
GFX/TEXTURES/CAVES/GREY + ALPHA/SW.PNG=GFX/TEXTURES/CAVES/GREY + ALPHA/SW.PNG
GFX/TEXTURES/CAVES/GREY + ALPHA/SW_F.PNG=GFX/TEXTURES/CAVES/GREY + ALPHA/SW_F.PNG
GFX/TEXTURES/CAVES/GREY + ALPHA/W.PNG=GFX/TEXTURES/CAVES/GREY + ALPHA/W.PNG
GFX/TEXTURES/CAVES/GREY/E.PNG=GFX/TEXTURES/CAVES/GREY/E.PNG
GFX/TEXTURES/CAVES/GREY/F.PNG=GFX/TEXTURES/CAVES/GREY/F.PNG
GFX/TEXTURES/CAVES/GREY/F_SEA.PNG=GFX/TEXTURES/CAVES/GREY/F_SEA.PNG
GFX/TEXTURES/CAVES/GREY/F_SHORE.PNG=GFX/TEXTURES/CAVES/GREY/F_SHORE.PNG
GFX/TEXTURES/CAVES/GREY/N.PNG=GFX/TEXTURES/CAVES/GREY/N.PNG
GFX/TEXTURES/CAVES/GREY/NE.PNG=GFX/TEXTURES/CAVES/GREY/NE.PNG
GFX/TEXTURES/CAVES/GREY/NW.PNG=GFX/TEXTURES/CAVES/GREY/NW.PNG
GFX/TEXTURES/CAVES/GREY/ROCK.PNG=GFX/TEXTURES/CAVES/GREY/ROCK.PNG
GFX/TEXTURES/CAVES/GREY/S.PNG=GFX/TEXTURES/CAVES/GREY/S.PNG
GFX/TEXTURES/CAVES/GREY/SE.PNG=GFX/TEXTURES/CAVES/GREY/SE.PNG
GFX/TEXTURES/CAVES/GREY/STALAGMITE.PNG=GFX/TEXTURES/CAVES/GREY/STALAGMITE.PNG
GFX/TEXTURES/CAVES/GREY/STALAGMITE_2.PNG=GFX/TEXTURES/CAVES/GREY/STALAGMITE_2.PNG
GFX/TEXTURES/CAVES/GREY/SW.PNG=GFX/TEXTURES/CAVES/GREY/SW.PNG
GFX/TEXTURES/CAVES/GREY/W.PNG=GFX/TEXTURES/CAVES/GREY/W.PNG
GFX/TEXTURES/DEMO/BARRIER.PNG=GFX/Textures/Demo/Barrier.png
GFX/TEXTURES/DEUR/DEUR HOUT 64X64.PNG=GFX/Textures/Deur/Deur Hout 64x64.png
GFX/TEXTURES/DUNGEON/GREY/ARCH+DOOR.PNG=GFX/TEXTURES/DUNGEON/GREY/ARCH+DOOR.PNG
GFX/TEXTURES/DUNGEON/GREY/ARCH.PNG=GFX/TEXTURES/DUNGEON/GREY/ARCH.PNG
GFX/TEXTURES/DUNGEON/GREY/FLOOR.PNG=GFX/TEXTURES/DUNGEON/GREY/FLOOR.PNG
GFX/TEXTURES/DUNGEON/GREY/SCHUIN_WALL_NORTH_EAST.PNG=GFX/TEXTURES/DUNGEON/GREY/SCHUIN_WALL_NORTH_EAST.PNG
GFX/TEXTURES/DUNGEON/GREY/SCHUIN_WALL_NORTH_WEST.PNG=GFX/TEXTURES/DUNGEON/GREY/SCHUIN_WALL_NORTH_WEST.PNG
GFX/TEXTURES/DUNGEON/GREY/WALL_EAST.PNG=GFX/TEXTURES/DUNGEON/GREY/WALL_EAST.PNG
GFX/TEXTURES/DUNGEON/GREY/WALL_NORTH.PNG=GFX/TEXTURES/DUNGEON/GREY/WALL_NORTH.PNG
GFX/TEXTURES/DUNGEON/GREY/WALL_SOUTH.PNG=GFX/TEXTURES/DUNGEON/GREY/WALL_SOUTH.PNG
GFX/TEXTURES/DUNGEON/GREY/WALL_WEST.PNG=GFX/TEXTURES/DUNGEON/GREY/WALL_WEST.PNG
GFX/TEXTURES/EFFECTS/NORTH-HOLE.PNG=GFX/Textures/Effects/North-Hole.png
GFX/TEXTURES/GENERAL SHAPES/SQUARE.PNG=GFX/Textures/General Shapes/Square.png
GFX/TEXTURES/GENERAL SHAPES/VLNW_TRIANGLE.PNG=GFX/Textures/General Shapes/VLNW_Triangle.png
GFX/TEXTURES/GENERAL SHAPES/VLSW_TRIANGLE.PNG=GFX/Textures/General Shapes/VLSW_Triangle.png
GFX/TEXTURES/GRASS/CAMPFIRE.PNG=GFX/TEXTURES/GRASS/CAMPFIRE.PNG
GFX/TEXTURES/GRASS/FLOWER.PNG=GFX/TEXTURES/GRASS/FLOWER.PNG
GFX/TEXTURES/GRASS/GRASS (GREEN).PNG=GFX/TEXTURES/GRASS/GRASS (GREEN).PNG
GFX/TEXTURES/HALFHOUTMUUR/RAAM.PNG=GFX/TEXTURES/HALFHOUTMUUR/RAAM.PNG
GFX/TEXTURES/HALFHOUTMUUR/ROOD.PNG=GFX/TEXTURES/HALFHOUTMUUR/ROOD.PNG
GFX/TEXTURES/HALFHOUTMUUR/ROOD_LV.PNG=GFX/TEXTURES/HALFHOUTMUUR/ROOD_LV.PNG
GFX/TEXTURES/HALFHOUTMUUR/ROOD_RV.PNG=GFX/TEXTURES/HALFHOUTMUUR/ROOD_RV.PNG
GFX/TEXTURES/HUMAN VILLAGE/HOUSE.PNG=GFX/TEXTURES/HUMAN VILLAGE/HOUSE.PNG
GFX/TEXTURES/HUMAN VILLAGE/INSIDE/BED.PNG=GFX/Textures/Inside House/Meubels/Bed.png
GFX/TEXTURES/HUMAN VILLAGE/INSIDE/HOUTEN RAND - HORIZONTAAL.PNG=src/Assets/Man Of Steel/GFX/Textures/Inside House/Houten Rand - Horizontaal.png
GFX/TEXTURES/HUMAN VILLAGE/INSIDE/HOUTEN RAND - VERTICAAL.PNG=GFX/Textures/Inside House/Houten Rand - Verticaal.png
GFX/TEXTURES/HUMAN VILLAGE/INSIDE/HOUTEN VLOER.PNG=GFX/Textures/Inside House/Houten Vloer.png
GFX/TEXTURES/HUMAN VILLAGE/INSIDE/STOEL - ACHTERZIJDE.PNG=GFX/Textures/Inside House/Meubels/Stoel Achterzijde.png
GFX/TEXTURES/HUMAN VILLAGE/INSIDE/STOEL - VOORZIJDE.PNG=GFX/Textures/Inside House/Meubels/Stoel Voorzijde.png
GFX/TEXTURES/HUMAN VILLAGE/INSIDE/TAFEL - KORT.PNG=GFX/Textures/Inside House/Meubels/Tafel - Kort.png
GFX/TEXTURES/HUMAN VILLAGE/INSIDE/TAFEL - MIDDEL.PNG=GFX/Textures/Inside House/Meubels/Tafel - Middel.png
GFX/TEXTURES/HUMAN VILLAGE/INSIDE/TAPIJT IN STUKJES.JPBF=GFX/Textures/Tapijt/Rood.jpbf
GFX/TEXTURES/HUMAN VILLAGE/INSIDE/TAPIJT.PNG=GFX/Textures/Tapijt/Tapijt.png
GFX/TEXTURES/HUMAN VILLAGE/INSIDE/TOONBANK.PNG=GFX/Textures/Inside House/Store/Toonbank.png
GFX/TEXTURES/HUMAN VILLAGE/INSIDE/WAND - LINKS.PNG=GFX/TEXTURES/HUMAN VILLAGE/INSIDE/WAND - LINKS.PNG
GFX/TEXTURES/HUMAN VILLAGE/INSIDE/WAND - RECHTS.PNG=GFX/Textures/Inside House/Wand - Rechts.png
GFX/TEXTURES/HUMAN VILLAGE/INSIDE/WAND.PNG=GFX/Textures/Inside House/Wand.png
GFX/TEXTURES/HUMAN VILLAGE/STENEN MUUR - MIDDEN.PNG=GFX/Textures/Village/Stenen Muur - Midden.png
GFX/TEXTURES/HUMAN VILLAGE/WELL.PNG=GFX/Textures/Village Objects/Well.png
GFX/TEXTURES/KAPOT MUBILAIR/BANK.PNG=GFX/TEXTURES/KAPOT MUBILAIR/BANK.PNG
GFX/TEXTURES/KAPOT MUBILAIR/HEMELBED.PNG=GFX/TEXTURES/KAPOT MUBILAIR/HEMELBED.PNG
GFX/TEXTURES/KAST/POTTENKAST.PNG=GFX/Textures/Inside House/Meubels/Kast/Potten.png
GFX/TEXTURES/LAVA/LAVA.PNG=GFX/Textures/Lava/Lava.png
GFX/TEXTURES/MARBLE/DEUR.PNG=GFX/Textures/Marble/Deur.png
GFX/TEXTURES/MARBLE/FLOOR.PNG=GFX/TEXTURES/MARBLE/FLOOR.PNG
GFX/TEXTURES/MARBLE/HEK - HOEK - E.PNG=GFX/TEXTURES/MARBLE/HEK - HOEK - E.PNG
GFX/TEXTURES/MARBLE/HEK - HOEK - W.PNG=GFX/TEXTURES/MARBLE/HEK - HOEK - W.PNG
GFX/TEXTURES/MARBLE/HEK - VERTICAAL.PNG=GFX/TEXTURES/MARBLE/HEK - VERTICAAL.PNG
GFX/TEXTURES/MARBLE/HEK.PNG=GFX/TEXTURES/MARBLE/HEK.PNG
GFX/TEXTURES/MARBLE/PILLAR.PNG=GFX/Textures/Marble/Pillar.png
GFX/TEXTURES/MARBLE/TRAP.PNG=GFX/TEXTURES/MARBLE/TRAP.PNG
GFX/TEXTURES/MARBLE/WALL - N.PNG=GFX/TEXTURES/MARBLE/WALL - N.PNG
GFX/TEXTURES/MARBLE/WALL - NE.PNG=GFX/TEXTURES/MARBLE/WALL - NE.PNG
GFX/TEXTURES/MARBLE/WALL - NW.PNG=GFX/TEXTURES/MARBLE/WALL - NW.PNG
GFX/TEXTURES/MURAL/WENIARIA.PNG=GFX/Textures/Mural/Weniaria.png
GFX/TEXTURES/MUUR TOORTS/BRANDEND.JPBF=GFX/Textures/Muur Toorts/Brandend.jpbf
GFX/TEXTURES/MUUR TOORTS/UIT.PNG=GFX/Textures/Muur Toorts/Uit.png
GFX/TEXTURES/OBJECTS/BOEK.PNG=GFX/Textures/Objects/Boek.png
GFX/TEXTURES/OBJECTS/HUT.PNG=GFX/Textures/Objects/Hut.png
GFX/TEXTURES/OBJECTS/KAARS UIT.PNG=GFX/Textures/Objects/Kaars Uit.png
GFX/TEXTURES/OBJECTS/KAARS.JPBF=GFX/Textures/Objects/Kaars.jpbf
GFX/TEXTURES/OBJECTS/MIRROR OF INSANITY.PNG=GFX/Textures/Objects/Mirror of Insanity.png
GFX/TEXTURES/OBJECTS/PEDDESTAL.PNG=GFX/Textures/Objects/Peddestal.png
GFX/TEXTURES/OBJECTS/TORCH POST.JPBF=GFX/Textures/Objects/Torch Post.jpbf
GFX/TEXTURES/OBJECTS/WOONWAGEN.PNG=GFX/Textures/Objects/Woonwagen.png
GFX/TEXTURES/PATH OF MAGIC/BOTTOM.PNG=GFX/Textures/Path Of Magic/Bottom.png
GFX/TEXTURES/PATH OF MAGIC/PLATFORM WITH BOTTOM SIDE.PNG=GFX/Textures/Path Of Magic/Platform with bottom side.png
GFX/TEXTURES/PATH OF MAGIC/PLATFORM.PNG=GFX/Textures/Path Of Magic/Platform.png
GFX/TEXTURES/PATH OF MAGIC/SHADEDEXIT.PNG=GFX/Textures/Path Of Magic/ShadedExit.png
GFX/TEXTURES/SCENARIO/FEENATOMB/FEENATOMB.PNG=GFX/TEXTURES/SCENARIO/FEENATOMB/FEENATOMB.PNG
GFX/TEXTURES/SEAL/SEAL.JPBF=GFX/Textures/Seal/Seal.jpbf
GFX/TEXTURES/SHAPES/RUIT.PNG=GFX/Textures/Shapes/Ruit.png
GFX/TEXTURES/SIGNS/DUNGSIGN_PLAQUE.PNG=GFX/Textures/Signs/DungSign_Plaque.png
GFX/TEXTURES/SIGNS/INN.PNG=GFX/TEXTURES/SIGNS/INN.PNG
GFX/TEXTURES/SIGNS/ITEM SHOP.PNG=GFX/TEXTURES/SIGNS/ITEM SHOP.PNG
GFX/TEXTURES/SIGNS/WAND.PNG=GFX/Textures/Signs/Signs.png
GFX/TEXTURES/SIGNS/WEAPON SHOP.PNG=GFX/TEXTURES/SIGNS/WEAPON SHOP.PNG
GFX/TEXTURES/STAIRS/DOWN.PNG=GFX/Textures/Stairs/Down.png
GFX/TEXTURES/STAIRS/UP.PNG=GFX/Textures/Stairs/Up.png
GFX/TEXTURES/SWITCH/LEFT.PNG=GFX/TEXTURES/SWITCH/LEFT.PNG
GFX/TEXTURES/SWITCH/RIGHT.PNG=GFX/TEXTURES/SWITCH/RIGHT.PNG
GFX/TEXTURES/SWORDS/COMBINED.PNG=GFX/TEXTURES/SWORDS/COMBINED.PNG
GFX/TEXTURES/SWORDS/LEFT 2 RIGHT.PNG=GFX/TEXTURES/SWORDS/LEFT 2 RIGHT.PNG
GFX/TEXTURES/SWORDS/RIGHT 2 LEFT.PNG=GFX/TEXTURES/SWORDS/RIGHT 2 LEFT.PNG
GFX/TEXTURES/TAPIJT/BLAUW.JPBF=GFX/Textures/TAPIJT/Blauw.jpbf
GFX/TEXTURES/TAPIJT/BLAUW.PNG=GFX/TEXTURES/TAPIJT/BLAUW.PNG
GFX/TEXTURES/TAPIJT/GROEN.JPBF=GFX/Textures/Tapijt/Groen.jpbf
GFX/TEXTURES/TAPIJT/PAARS.JPBF=GFX/Textures/Tapijt/Paars.jpbf
GFX/TEXTURES/TOWN/ELVES/HOUSE.PNG=GFX/TEXTURES/TOWN/ELVES/HOUSE.PNG
GFX/TEXTURES/TREES/SPAR.PNG=GFX/TEXTURES/TREES/SPAR.PNG
GFX/TEXTURES/TREES/STRUIK.PNG=gfx/textures/Trees/struik.png
GFX/TEXTURES/WATER/WATER.PNG=GFX/TEXTURES/WATER/WATER.PNG
GFX/TEXTURES/WOOD/MUUR.PNG=GFX/Textures/Wood/Muur.png
GFX/TEXTURES/WOOD/VLOER.PNG=GFX/TEXTURES/WOOD/VLOER.PNG
GFX/TREASURE/BAG.PNG=GFX/Treasure/BAG.png
GFX/TREASURE/BLUE STAFF.PNG=GFX/Textures/Treasure/Blue Staff.png
GFX/TREASURE/CHEST.JPBF=GFX/Textures/Treasure/Chest.jpbf
GFX/TREASURE/MANAORB.PNG=GFX/TREASURE/MANAORB.PNG
[TRANSFER]
UNKNOWN_ALLOWED=Y
